_DEF_KWD(IF_STR, IF, IF_STR)
_DEF_KWD(WHILE_STR, WHILE, WHILE_STR)
_DEF_KWD("=", ASSIGN, "=")
_DEF_KWD(DECLARATION_STR, DECLARATION, DECLARATION_STR)

_DEF_KWD("sin", SIN, "sin")
_DEF_KWD("cos", COS, "cos")
_DEF_KWD("floor", FLOOR, "floor")
_DEF_KWD("+", ADD, "+")
_DEF_KWD("-", SUB, "-")
_DEF_KWD("*", MULT, "*")
_DEF_KWD("/", DIV, "/")
_DEF_KWD("sqrt", SQRT, "sqrt")
_DEF_KWD("^", POW, "^")

_DEF_KWD("==", EQUAL, "==")
_DEF_KWD("<", LESS, "\\<")
_DEF_KWD(">", GREATER, "\\>")
_DEF_KWD("<=", L_OR_EQ, "<=")
_DEF_KWD(">=", G_OR_EQ, ">=")
_DEF_KWD("!=", N_EQ, "!=")
_DEF_KWD("&&", AND, "&&")
_DEF_KWD("||", OR, "||")
_DEF_KWD("!", NOT, "!")

_DEF_KWD(";", SEMICOLON, ";")
_DEF_KWD(",", COMMA, ",")
_DEF_KWD("(", BRACKET_OP, "(")
_DEF_KWD(")", BRACKET_CL, ")")
_DEF_KWD("{", BRACE_OP, "{")
_DEF_KWD("}", BRACE_CL, "}")

_DEF_KWD(IN_STR, IN, IN_STR)
_DEF_KWD(OUT_STR, OUT, OUT_STR)

_DEF_KWD(RETURN_STR, RETURN, RETURN_STR)
_DEF_KWD(BREAK_STR, BREAK, BREAK_STR)
_DEF_KWD(CONTINUE_STR, CONTINUE, CONTINUE_STR)
_DEF_KWD("abort", ABORT, "abort")
